apiVersion: apps/v1
kind: Deployment
metadata:
  name: burry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burry
  template:
    metadata:
      labels:
        app: burry
    spec:
      containers:
      - name: url-shortener
        image: ghcr.io/gerrited/burry:latest
        ports:
        - containerPort: 8080
        env:
          - name: REDIS_ADDR
            value: "burry-cache:6379"

---

apiVersion: v1
kind: Service
metadata:
  name: burry
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: burry
