apiVersion: apps/v1
kind: Deployment
metadata:
  name: burry-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burry-cache
  template:
    metadata:
      labels:
        app: burry-cache
    spec:
      containers:
      - name: burry-cache
        image: redis:alpine
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: burry-cache
spec:
  ports:
    - port: 6379
  selector:
    app: burry-cache
