apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dotnet-webapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dotnet-webapi
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50