apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-k3s-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgC3DnmusJuD1PK1OsL1EXPEYCFu2OW0oIrWIT78D3u0JNvcOSlcmNVUEqC6b8Co3ulnig24sxfo8BKj5IEq6a/dR4fq5eJhKO4Q4SKG8nguCrI6JSjQmVX/9+ZngLVzfniqwSP1PsIm4d7rNC1OlAdJo1p7CkY67qHz7+dL1aExb6Sbntt794PhCKZDs8EJAGmRMUGwUecgIVPur+bHt69ZJSF+nugj/jeNAQUARHgeIcoaO8TroqKnK/oHB661hqzRCtyzr1rFoIDhfanT5xqU0O4vmenvW9Xy5UwnOCtw6tOBApu0+Tgz4BDyvsI/POgzi2j9IfQsupqaecXIyTyIw+zxaMBhgxkKEnzRNl94LEFU3pCwwjOUry9y9QteVxIj5CdA0U+75dAFU8u4p3+dG4KE7BcDE7E5FhNk9TbRy1kjU6dFiFsEGo643EL+YBW1nHgwdZdKsQ378ui0JHRHA2jKozKaZDtSWlvfCMNZcsQLzalR9RVwigvwGn4PFcQ1skhFVlrtMwd2JE/KUAoqGkxNYQBVD4BoYy+kTqo90wU3f0eymYdmtHhgoG0Vc4TACPyZGbuVuUrxkiTMa2/GBZRmRro8Oc0PraTqZOeuGROc7Jh4UQqwtuIJpCmFQnIrd6eY6+zKycnty3TulsNkGvFVAgCNkYWkB91p/WGw9R/rssD/VOXeY6pbVQ1mpmUjKgon30w/GxIWtEY2Tj4ODh8zkxRtclc0+ss+eloajmQXug83og4uctOauvnBy6i79dkoMKP/zdGsrCEh5f8KqHu2iecB6sAS5ZOCViR9y2pgRiDDXmDjUqAj1oVnWZ1e9r9Tu3tw8QNqZqoBbmowqAJc8FNwcsEywSsTx+mQw34Ovl5fK5XmRA902hL8ZpYieBWi2sutF8wkAeJjkte1WMxfkGzO7wFvmftQBbPcX5TiELo=
  template:
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:credentials.json: {}
          f:type: {}
        manager: kubectl-create
        operation: Update
        time: "2023-03-03T18:20:43Z"
      name: tunnel-k3s-credentials
      namespace: default
    type: Opaque

