apiVersion: apps/v1
kind: Deployment
metadata:
  name: daily-workout
  labels:
    app: daily-workout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daily-workout
  template:
    metadata:
      labels:
        app: daily-workout
    spec:
      containers:
      - name: daily-workout
        image: ghcr.io/gerrited/daily-workout:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - mountPath: "/usr/src/app/data"
          name: workout-volume
      volumes:
      - name: workout-volume
        persistentVolumeClaim:
          claimName: workout-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: daily-workout
spec:
  selector:
    app: daily-workout
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
