apiVersion: batch/v1
kind: CronJob
metadata:
  name: workout-generator
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: generate-workout
            image: ghcr.io/gerrited/workout-generator:latest
            volumeMounts:
            - name: workout-volume
              mountPath: "/usr/src/app/data"
            env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: daily-workout
                  key: OPENAI_API_KEY
          restartPolicy: OnFailure
          volumes:
          - name: workout-volume
            persistentVolumeClaim:
              claimName: workout-pvc
