apiVersion: batch/v1
kind: CronJob
metadata:
  name: workout-generator
spec:
  schedule: "0 0 * * *"  # Täglich um Mitternacht
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: generate-workout
            image: ghcr.io/gerrited/workout-generator:latest
            volumeMounts:
            - name: workout-volume
              mountPath: "/usr/src/app/data"
          restartPolicy: OnFailure
          volumes:
          - name: workout-volume
            persistentVolumeClaim:
              claimName: workout-pvc
