apiVersion: v1
kind: PersistentVolume
metadata:
  name: workout-pv
spec:
  capacity:
    storage: 100m
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/workout"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workout-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100m
